name: Docker Image CI

on: [push]

jobs:

   build:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v1
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag docker.pkg.github.com/hochen97/golinks/golinks:$(date +%s)
       
     - name: Login to the package registry
       run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       
     - name: Push to the package registry
       run: docker push docker.pkg.github.com/hochen97/golinks/golinks:$(date +%s)
